apps/voters/urls.py
from django.urls import path
from .views import HomeView, VotersFormView, VotersUpdateView, VoterListView, VoterListCreate, ConsultAPIView, DashboardView
from .reporte import reportVoter, reportUserParent, reportByQuarter, reportByVotingPoint
app_name = 'apps.voters'


urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('voters/', VoterListView.as_view(), name='voter-list'),
    path('voter',VotersFormView.as_view(), name='voter'),
    path('voter/<pk>/edit',VotersUpdateView.as_view(), name='voter-edit'),
    
    path('api/v1/voters/', VoterListCreate.as_view(), name='voters_list_create'),
    path('api/v1/consult/', ConsultAPIView.as_view()),
    path('report',reportVoter, name="report-voter"),
    path('report/parent',reportUserParent, name="report-parent"),
    path('report/quarter', reportByQuarter, name='report-quarter'),
    path('report/votingPoint', reportByVotingPoint, name='report-votingPoint'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('select2/', include('django_select2.urls')),
    path('', include('apps.voters.urls', namespace="voter")),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/voters/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

DOCUMENT_TYPES = [
    ('CC','CEDULA DE CIUDADANIA'),
    ('CE','CEDULA DE EXTRANJERIA'),
]

class VotingPoint(models.Model):
    name =          models.CharField(max_length=200)
    longitude =     models.DecimalField(max_digits=9, decimal_places=6) 
    latitude =      models.DecimalField(max_digits=10, decimal_places=6)
    department =    models.CharField(max_length=50, blank=True)
    municipality =  models.CharField(max_length=50, blank=True)
    
    def __str__(self):
        self.name = self.name.upper()
        return self.name

class Quarters(models.Model):
    name =      models.CharField(max_length=200)
    commune =   models.CharField(max_length=50)
    def __str__(self):
        self.name = self.name.upper()
        return self.name
    
class OfficialConsultation(models.Model):
    nuip =          models.CharField(max_length=11)
    department =    models.CharField(max_length=50, blank=True)
    municipality =  models.CharField(max_length=50, blank=True)
    point =         models.CharField(max_length=50)
    address =       models.CharField(max_length=100)
    table =         models.IntegerField()

    def save(self, *args, **kwargs):
        self.department = self.department.upper()
        self.municipality = self.municipality.upper()
        self.point = self.point.upper()
        self.address = self.address.upper()
        super().save(*args, **kwargs)

    def __str__(self):
        return self.nuip
    
class Voter(models.Model):
    document_type =             models.CharField(max_length=2, choices=DOCUMENT_TYPES, default='CC', blank=True)
    nuip =                      models.CharField(max_length=11, unique=True)
    full_name =                 models.CharField(max_length=100)
    
    parent_voter =              models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL)
    parent_voter_count =        models.IntegerField(default=0,blank=True)
    
    quarter =                   models.ForeignKey(Quarters, on_delete=models.CASCADE, blank=True,null=True)
    address =                   models.CharField(max_length=100, blank=True)
    phone =                     models.CharField(max_length=20, blank=True)
    email =                     models.EmailField(max_length=100, blank=True)
    created_at =                models.DateTimeField(auto_now_add=True)
    update_at =                 models.DateField(auto_now=True,blank=False)
    voting_point =              models.ForeignKey(VotingPoint, on_delete=models.CASCADE, related_name='voters',blank=True,null=True)  
    coordinator =               models.ForeignKey(User, on_delete=models.CASCADE, blank=True)
    official_consultation =     models.ForeignKey(OfficialConsultation, on_delete=models.CASCADE, blank=True,null=True)
    checkout =                  models.BooleanField(default=False)
    checkout_confirmation =     models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        self.full_name = self.full_name.upper()
        self.address = self.address.upper()

        super().save(*args, **kwargs)

    def __str__(self):
        return self.full_name

    @property
    def related_count(self):
        return Voter.objects.filter(parent_voter=self).count()

class UserParent(models.Model):
    user =      models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    parent =    models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, related_name='children')

    def __str__(self):
        return self.user.username

class SharedToken(models.Model):
    key = models.CharField(max_length=32, unique=True,blank=True)
    def save(self, *args, **kwargs):
        if not self.key:    
            self.key = uuid.uuid4().hex
        super().save(*args, **kwargs)

apps/voters/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Voter, VotingPoint, Quarters
from django_select2.forms import Select2Widget

DEFAULT_ATTRS = {
    'autocomplete': 'off',
    'class': 'w-full border-2 bg-white border-white mt-3 text-gray mb-4 max-w-lg block focus:ring-indigo-500 focus:border-gray-500 sm:max-w-xs sm:text-sm rounded-full border-width-4'
}
TEXTAREA_ATTRS = {
    'autocomplete': 'off',
    'class': 'w-full border-2 bg-white border-white mt-1 mb-4 max-w-lg block focus:ring-indigo-500 focus:border-gray-500 sm:max-w-xs sm:text-sm rounded-lg border-width-4'
}

def create_charfield(name, placeholder, min_length=None, max_length=None, type='text'):
    widget = forms.TextInput(attrs={
        **DEFAULT_ATTRS, 'placeholder': placeholder
    })
    if type =='textarea':
        widget = forms.Textarea(attrs={
            **DEFAULT_ATTRS, "rows": "2", 'placeholder': placeholder
        })


    return forms.CharField(
        min_length=min_length,
        max_length=max_length,
        widget=widget,
        required=True
    )

class VotersForm(forms.ModelForm):
    DOCUMENT_TYPES = [
        ('CC','CEDULA DE CIUDADANIA'),
        ('CE','CEDULA DE EXTRANJERIA'),
    ]

    document_type = forms.ChoiceField(choices=DOCUMENT_TYPES, widget=forms.Select(attrs=DEFAULT_ATTRS), required=True)

    nuip = create_charfield('nuip', 'Ingrese el Numero de Identidad', min_length=7, max_length=10)

    full_name = create_charfield('full_name', 'Ingrese el Nombre completo')

    parent_voter_count = forms.IntegerField(widget=forms.TextInput(attrs={**DEFAULT_ATTRS, 'placeholder': 'Ingrese el Numero de Integrantes'}),required=False)
    
    quarter = quarter = forms.ModelChoiceField(queryset=Quarters.objects.all().order_by('name'), empty_label="Selecciona un barrio o vereda", widget=Select2Widget(attrs=DEFAULT_ATTRS), required=True)

    address = forms.CharField(widget=forms.Textarea(attrs={**TEXTAREA_ATTRS, 'placeholder': 'Direccion (Opcional)', type: 'textarea', 'rows': 2}),max_length=150,required=False)
    
    phone = create_charfield('phone', 'Número de teléfono', min_length=10, max_length=10)

    voting_point = forms.ModelChoiceField(queryset=VotingPoint.objects.all(),empty_label="Selecciona un punto de votación", widget=Select2Widget(attrs=DEFAULT_ATTRS),required=True)  

    email = forms.EmailField(widget=forms.EmailInput(attrs={**DEFAULT_ATTRS, 'placeholder': 'Ingrese el Correo Electrónico'}), required=False)

    def clean_fields(self):
        super().clean_fields()
        
        document_type = self.cleaned_data.get('document_type')
        if document_type not in [doc_type[0] for doc_type in self.DOCUMENT_TYPES[1:]]: 
            self.add_error('document_type', "Por favor selecciona un tipo de documento valido.")
            
        nuip = self.cleaned_data.get('nuip')
        if not nuip.isdigit():
            self.add_error('nuip', "El Numero de identidad debe contener únicamente dígitos numéricos.")
        elif len(nuip) < 7 or len(nuip) > 10:
            self.add_error('nuip', "El Numero de identidad debe tener un mínimo de 7 y un máximo de 10 dígitos.")
        
        phone = self.cleaned_data.get('phone')
        if len(str(phone)) != 10 or not str(phone).startswith('3'):
            self.add_error('phone', "El número de telefono debe tener 10 digitos y comenzar con 3")
        
        address = self.cleaned_data.get('address')
        if address and len(address) > 150: 
            self.add_error('address', "La dirección debe tener un máximo de 150 caracteres.")

    class Meta:
        model = Voter
        fields = ['document_type', 'nuip', 'full_name', 'parent_voter_count','quarter', 'voting_point', 'phone', 'email', 'address']

apps/voters/views.py
from django.contrib import messages 
from django.contrib.auth.mixins import  LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import ListView
from django.utils import timezone
from .forms import VotersForm
from .models import Voter,SharedToken
from .serializers import VoterSerializer, ConsultSerializer
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status, exceptions, generics
from rest_framework.authentication import BaseAuthentication
from django.utils import timezone
import json
class SharedTokenAuthentication(BaseAuthentication):
    def authenticate(self, request):
        token = request.META.get('HTTP_AUTHORIZATION')
        if not token:
            return None
        try:
            SharedToken.objects.get(key=token)
        except SharedToken.DoesNotExist:
            raise exceptions.AuthenticationFailed('No such token')

        return (None, None)

class ConsultAPIView(APIView):
    authentication_classes = [SharedTokenAuthentication]
    def get_new_nuip(self):
        new_nuip_object = Voter.objects.filter(checkout=False).first()
        if new_nuip_object:
            return new_nuip_object.nuip
        else:
            return 'Ya no hay NUIP para verificar'
    def post(self, request, *args):
        nuip = request.data.get('nuip')
        current_department = request.data.get('department')
        current_municipality = request.data.get('municipality')
        if not nuip:
            return Response({
                'success': True,
                'new_nuip': self.get_new_nuip()
            }, status=status.HTTP_200_OK)
        try:
            voter = Voter.objects.get(nuip=nuip)
        except Voter.DoesNotExist:
            return Response({'error': 'Votante no registrado en la base de datos SS'}, status=status.HTTP_404_NOT_FOUND)
        serializer = ConsultSerializer(data=request.data)
        if serializer.is_valid():
            official_consultation = serializer.save()
            if voter.voting_point.department != current_department or voter.voting_point.municipality != current_municipality:
                voter.checkout_confirmation = False
            else:
                if not voter.checkout_confirmation:
                    voter.checkout_confirmation = True
            if voter.checkout:
                return Response({'error': 'El votante ya esta validado'}, status=status.HTTP_400_BAD_REQUEST)
            else:
                voter.official_consultation = official_consultation
                voter.checkout = True
                voter.update_at = timezone.now()
                voter.save()
                return Response({
                    'success': True,
                    'new_nuip': self.get_new_nuip()
                }, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

class VoterListCreate(generics.ListCreateAPIView):
    queryset = Voter.objects.all()
    serializer_class = VoterSerializer
    
class CreateUpdateMixin(LoginRequiredMixin, View):
    def process_form(self, request, form, instance=None):
        if form.is_valid():
            form.instance.coordinator = request.user
            if instance:
                form.instance.id = instance.id
            form.save()
            messages.success(request, f'Votante {"actualizado" if instance else "registrado"} con éxito')
            return redirect('voter:voter-list')
        else:
            for field, errors in form.errors.items():
                for error in errors:
                    if "already exists" in error:
                        error = "Ya existe un Votante registrado con esa Cedula."
                    messages.error(request, f"{error}")
        
        return render(request, self.template_name, {'form': form})

class HomeView(View):
    template_name ='home.html'
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('voter:dashboard')
        return render(request, self.template_name)

class DashboardView(LoginRequiredMixin,View):
    template_name ='dash.html'
    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)
    
class VoterListView(LoginRequiredMixin, ListView):
    model = Voter
    context_object_name = 'voters'
    template_name = 'voters_list.html'
    paginate_by = 5

    def get_queryset(self):
        return Voter.objects.filter(coordinator=self.request.user)

class VotersFormView(CreateUpdateMixin):
    template_name = 'voters.html'
    form_class = VotersForm

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            parent_voter = form.save(commit=False) 
            parent_voter.coordinator = request.user 
            parent_voter.save()  
            child_voters_data_str = request.POST.get('child_voters_data', '[]')
            print(child_voters_data_str)
            if child_voters_data_str:
                child_voters_data = json.loads(child_voters_data_str)
            else:
                child_voters_data = []
            print(child_voters_data)
            for child_data in child_voters_data:
                Voter.objects.create(
                    parent_voter=parent_voter,
                    document_type=child_data.get('document_type', 'CC'),
                    nuip=child_data.get('nuip'),
                    full_name=child_data.get('full_name'),
                    coordinator=request.user,
                )
        return self.process_form(request, form)
    
class VotersUpdateView(CreateUpdateMixin):
    template_name="votersEdit.html"
    form_class=VotersForm

    def get(self, request, *args, **kwargs):
        voter = Voter.objects.get(pk=kwargs['pk'])
        form = self.form_class(instance=voter)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        voter = Voter.objects.get(pk=kwargs['pk'])
        form = self.form_class(request.POST, request.FILES, instance=voter)
        if 'voter_edits' not in request.session or request.session['voter_edits_date'] != timezone.now().date().isoformat():
            request.session['voter_edits'] = 0
            request.session['voter_edits_date'] = timezone.now().date().isoformat()

        if request.session['voter_edits'] < 3:
            voter.update_add = timezone.now()  
            voter.save()
            return self.process_form(request, form, instance=voter)

        messages.error(request, 'Has llegado al límite de ediciones diarias.')
        return redirect('voter:voter-list')

templates/base.html
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="es" class="scroll-smooth" data-theme="themeOrange" prefix="og:https://ogp.me/ns/website#">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/site.webmanifest">
    <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#c0d8fc">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="static/assets/css/s-styles.css">

    <link rel="shortcut icon" href="" type="image/x-icon">
    <link href="" rel="apple-touch-icon">


    {% tailwind_css %}
    <!--Alpine JS-->
    
    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.8.2/dist/alpine.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@2.8.2/dist/alpine.min.js" defer></script>
    <!--Boxicons-->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap">

    <meta name="author" content="Social System">
    <title>Social System</title>
    <meta name="description" content="">
    <link href="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/css/tom-select.css" rel="stylesheet">
      <script src="https://cdn.jsdelivr.net/npm/tom-select@2.2.2/dist/js/tom-select.complete.min.js"></script>

</head>
{% if messages %}
{% include 'messages.html' %}
{% endif %}
<body class="flex flex-col justify-center items-center min-h-screen bg-base-200">

 
  

{% block content %}
{% endblock content %}



  
    <!-- Footer -->
    
    <script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>


</body>
  
</html>

templates/home.html
{% load static %}
{% include "base/head.html" %}
{% include "messages.html" %}

{% block content %}
<section x-data="{ showButton: false }" class="flex flex-col justify-center items-center h-screen w-full">
    <div class="p-6">
        <div class="animate-zoom-in md:mx-auto text-center">
            <img @click="showButton = true" src="{% static 'assets/img/ssblanco.svg' %}" class="w-32 max-w-2xl mx-auto opacity-1 cursor-pointer" alt="Logo ss" />
        </div>
        
        <p class="eslogan text-white text-center mt-8">El app ideal, para mantener a todos sus usuarios registrados.</p>

        <div class="mt-6 text-center">
          <!-- Aquí aplicamos el estilo del botón con un buen contenedor y más largo en los lados -->
          <a href="{% url 'account_login' %}" id="ingresaButton" style="opacity: 0;" class="custom-button-login inline-block bg-transparent text-white font-bold text-3xl py-3 px-8 rounded-full border-4 border-white transition-all duration-300 ease-in-out transform translate-y-4 hover:bg-white hover:text-blue-500 hover:opacity-100 translate-y-0">Ingresa</a>
        </div>
        
    </div>
</section>



{% endblock content %}

{% block js %}
<script>
    function initButton() {
        const isFirstVisit = localStorage.getItem('isFirstVisit');
        if (!isFirstVisit) {
            setTimeout(() => {
                document.getElementById('ingresaButton').style.opacity = 1;
            }, 3000);
            localStorage.setItem('isFirstVisit', 'true');
        } else {
            setTimeout(() => {
                document.getElementById('ingresaButton').style.opacity = 1;
            }, 1000);
        }
    }
    
    window.onload = initButton;
</script>
{% endblock js %}

templates/voters.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<main class="main bg-gradient-to-b from-[#6792EB] to-[#535CD4] text-gray-900 flex flex-col justify-center items-center w-full min-h-screen">
    <div class="hero w-full flex-grow" id="inicio">
        <div class="flex flex-col justify-center items-center min-h-screen text-gray-900">
            <a href="{% url 'voter:home' %}">
                <img class="h-12 w-auto" src="{% static 'assets/img/ssblanco.svg' %}" alt="">
            </a>
            <div class="flex flex-wrap justify-center py-6">
                <div class="container mx-auto">
                    <div class="flex items-center justify-between flex-wrap sm:flex-nowrap">
                        <div class="mt-2">
                            <h1 class="text-center text-xl text-white font-bold">
                                Completa la siguiente informacion
                            </h1>
                            <video id="video" style="width: 100%; height: auto;"></video>
                            <div class="text-center">
                                <button id="startButton" class="mx-auto rounded-full mx-auto bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Comenzar Lectura</button>
                            </div>
                            <form class="w-full max-w-sm space-y-6 px-2" method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div>
                                <label for="document_type" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Tipo de Documento *
                                </label>
                                    {{form.document_type}}
                                <label for="nuip" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Numero de Identidad *
                                </label>
                                    {{form.nuip}}
                                <label for="full_name" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Nombre Completo *
                                </label>
                                    {{form.full_name}}
                                <label for="quarter" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Barrio *
                                </label>
                                    {{form.quarter}}
                                <label for="parent_voter_count" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Referidos *
                                </label>
                                    {{form.parent_voter_count}}
                                <label for="address" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Dirección (opcional)
                                </label>
                                    {{form.address}}
                                <label for="phone" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Numero Telefónico *
                                </label>
                                    {{form.phone}}
                                <label for="email" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                        E-mail (opcional)
                                </label>
                                        {{form.email}}
                                <label for="voting_point" class="block text-sm font-medium text-white pl-2 mb-1 mt-2 ">
                                    Punto de Votación *
                                </label>
                                    {{form.voting_point}}
                                <input type="hidden" id="child_voters_data" name="child_voters_data">
                                <div class="control-group">
                                    <div class="controls">
                                        <button type="submit" class="border-2 border-white mt-4 rounded-full flex justify-center py-2 px-4 mx-auto shadow-sm text-xl text-white bg-[#6792EB] hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                                            Guardar
                                        </button>
                                    </div>
                                </div>
                                </div>
                                
                            </form>
                            <div id="myModal" class="modal">
                                <div class="modal-content">
                                    <span class="close">&times;</span>
                                    <div id="additional_form_container"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</main>
{% block js %}
<script>
    window.onload = function() {
        var settings = {};
        //search for all elements with the class "django-select2"
        var elements = document.querySelectorAll('.django-select2');
        //loop through all found elements
        for (var i = 0; i < elements.length; i++) {
            //create a new TomSelect element for each
            new TomSelect(elements[i], settings);
        }

        ///scan barcode
        const video = document.getElementById('video');
        const detectionBox = document.getElementById('detectionBox');
        const startButton = document.getElementById('startButton');

        // Check if barcode detection is supported
        if (!('BarcodeDetector' in window)) {
            console.error('Barcode detection is not supported on this browser.');
            startButton.disabled = true;
            return;
        }

        const barcodeDetector = new BarcodeDetector({ formats: ['pdf417'] });
        const textDecoder = new TextDecoder();
        let scanning = false;

        async function startScanner() {
            try {
                const stream = await navigator.mediaDevices.getUserMedia({ video: true });
                video.srcObject = stream;
                video.addEventListener('loadeddata', handleVideoLoaded);
            } catch (error) {
                console.error('Error accessing camera: ', error);
            }
        }

        function handleVideoLoaded() {
            video.play();
            scanning = true;
            scanBarcode();
        }

        async function scanBarcode() {
            if (!scanning) return;

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;

            const context = canvas.getContext('2d');
            context.drawImage(video, 0, 0, canvas.width, canvas.height);

            try {
                const barcodes = await barcodeDetector.detect(canvas);
                if (barcodes && barcodes.length > 0) {
                    // Get the barcode result for further processing
                    const barcodeResult = barcodes[0];
                    console.log('Barcode detected:', barcodeResult);
                    // Extract the relevant information from the barcode
                    const { x, y, width, height } = barcodeResult.boundingBox;

                    // Update the detection box position and size
                    detectionBox.style.left = `${x}px`;
                    detectionBox.style.top = `${y}px`;
                    detectionBox.style.width = `${width}px`;
                    detectionBox.style.height = `${height}px`;

                    // Decode and convert binary data to readable format
                    const binaryData = barcodeResult.rawData;
                    const decodedData = textDecoder.decode(binaryData);
                    console.log('Decoded data:', decodedData);

                    // Stop scanning after detecting a barcode
                    scanning = false;
                }

                // Continue scanning for barcodes
                if (scanning) {
                    requestAnimationFrame(scanBarcode);
                }
            } catch (error) {
                console.error('Error scanning barcode:', error);
            }
        }

        startButton.addEventListener('click', startScanner);
    };
    $(document).ready(function(){
        var modal = document.getElementById("myModal");
    
        $('#id_parent_voter_count').change(function(){
            var parent_voter_count_num = $(this).val();
            var container = $('#additional_form_container');
            container.empty();
            for(let i = 0; i < parent_voter_count_num; i++) {
                var form = '<div><input type="text" id="child_nuip_'+i+'" name="child_nuip_'+i+'" placeholder="No. Cédula"><input type="text" id="child_name_'+i+'" name="child_name_'+i+'" placeholder="Nombre completo"></div>';
                container.append(form);
            }
            if(parent_voter_count_num > 0) {
                var submit_button = '<button type="button" id="collect_data_button">Finalizar Referidos</button>';
                container.append(submit_button);
                modal.style.display = "block"; 
            }
        });
        
        $('form').on('submit', function(event){
            event.preventDefault();
            var parent_voter_count_num = $('#id_parent_voter_count').val();
            var child_voters_data = [];
    
            for(let i = 0; i < parent_voter_count_num; i++) {
                let child_nuip = $('#child_nuip_'+i).val();
                let child_name = $('#child_name_'+i).val();
    
                // Tomamos los datos de los input fields y creamos un objeto de votante hijo.
                let child_voter_data = {
                    'nuip': child_nuip,
                    'full_name': child_name,
                }
                // Añadimos el objeto al array de datos de votantes hijo.
                child_voters_data.push(child_voter_data);
            }
    
            // Convertimos el array de datos de votantes hijo a una cadena en formato JSON y lo asignamos al input field.
            $('#child_voters_data').val(JSON.stringify(child_voters_data));
            
            // Cerramos el modal después de recoger todos los datos.
            modal.style.display = "none"; 
    
            // Enviamos el formulario manualmente.
            this.submit();
        });
    });
</script>
<style>
    .ts-control {
        border-radius: 9999px !important;
    }
</style>
{% endblock js %}


{% endblock content %}